apiVersion: v1
kind: Service
metadata:
  name: k8s-web-hello
spec:
  type: LoadBalancer   # Permet d'exposer le service en externe
  selector:
    app: k8s-web-hello
  ports:
  - port: 3030       # Port exposé par le service
    targetPort: 3000 # Port sur lequel les pods écoutent
  

